### ISSUE TITLE
add to crates.io?

### ISSUE THREAD

**Issue by vitiral** [bodil/newtype-proxy#2]
Hey, I just came across this library and like it much better than the macro-based ones. Any chance you can add it to crates.io?

Thanks!

**Comment by dpc** [comment]
Bump.

**Comment by bodil** [comment]
No, sorry, this project is not maintained, and it was never a good idea in the first place.

**Comment by mgsloan** [comment]
Hmm, can you please explain why it isn't a good idea?  As a Rust beginner and Haskell afficianado (fan of GeneralizedNewtypeDeriving), this seems like it's along the lines of what I want.  https://docs.rs/newtype_derive/0.1.6/newtype_derive/ seems very limited.

**Comment by mgsloan** [comment]
Ohh, nvm, seems like newtype_derive is a superset of the capabilities of newtype-proxy

**Comment by bodil** [comment]
There's also https://crates.io/crates/derive_more which has the same derives for `From` and `Deref` plus a lot more.

I generally prefer wrapping the required methods manually, for the sake of explicitness (which is also why I try to avoid `use crate::*;`), but I'll admit sometimes that's just too much work.

**Comment by mgsloan** [comment]
Thanks for explaining and linking to derive_more, @bodil!  I found https://crates.io/crates/shrinkwraprs , but it gives a lot less control and isn't used much.  Looks like a subset of the functionality.  Time to switch over to derive_more!

Yes, explicitness can be good.  However, there's always a decision between using a Haskell-style newtype and the inner type.  I find the extra type checking and signature clarity of wrapping lots of stuff in newtypes to be quite helpful.  Lots of explicit boilerplate makes each newtype much more expensive in code size, which would disincentivize usage.  There will only be large adoption of decent type safety / powerful checking if it's made convenient and easy.  So, that's why I'm keen on powerful newtype deriving in rust!

Would also like to have Haskell's zero-cost safe coerce mechanism, but haven't been able to find anything like it

**Comment by mgsloan** [comment]
I realize this is probably not the best spot to ask about it, but I haven't found any way to newtype derive an AsRef trait.  shrinkwrapprs will generate one that gives the inner type, but doesn't generate any other AsRef impls.  For example, if I am wrapping a `PathBuf`, I still want `AsRef<Path>` for my wrapper.  Is there a decent way?

**Comment by bodil** [comment]
Sorry, haven't seen any.
